version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SHARDS_CACHE_PATH=/app/.shards
      - DATABASE_URL=postgres://postgres:postgres@db/hutchison
    volumes:
      - .:/app
    command: >
      bash -c "nf start -j Procfile.dev"
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      - internal
      - external
    links:
      - db

  build:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PATH: /db/hutchison_animals.db
    volumes:
      - .:/app
    command: >
      bash -c "crystal build src/hutchison-animals.cr --release -o ./hutchison-animals"

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: hutchison
    volumes:
      - data:/var/lib/postgres/data
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - internal

networks:
  external:
  internal:

volumes:
  data:
