version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SHARDS_CACHE_PATH: /app/.shards
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app
    command: >
      bash -c "sqlite3 ./db/hutchison_animals.db < db/migrations.sql
      && nodemon --exec crystal run src/hutchison-animals.cr"
    ports:
      - 3000:3000
    networks:
      - external

networks:
  external:
