version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SHARDS_CACHE_PATH: /app/.shards
      DB_PATH: db/hutchison_animals_dev.db
    volumes:
      - .:/app
    command: >
      bash -c "sqlite3 $${DB_PATH} < db/migrations.sql
      && nf start -j Procfile.dev"
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      - external

  test:
    << : *app
    environment:
      DB_PATH: /tmp/hutchison_animals_test.db
    command: >
      bash -c "sqlite3 $${DB_PATH} < db/migrations.sql
      && KEMAL_ENV=test DB_PATH=$${DB_PATH} crystal spec"

  build:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PATH: /db/hutchison_animals.db
    volumes:
      - .:/app
    command: >
      bash -c "crystal build src/hutchison-animals.cr --release -o ./hutchison-animals"

networks:
  external:
